name: Build the PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'code/**'
      - 'test/**'
      - 'DB/Schemas/**'
    branches:
      - master
      - main  # Added main branch for completeness
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build request'

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Check Python Version
              id: python-check
              run: |
                if command -v python3.13 &> /dev/null; then
                  echo "Python 3.13 is already installed"
                  echo "skip-python-setup=true" >> $GITHUB_OUTPUT
                elif command -v python3 &> /dev/null && python3 --version | grep -q "Python 3.13"; then
                  echo "Python 3.13 is already installed"
                  echo "skip-python-setup=true" >> $GITHUB_OUTPUT
                else
                  echo "Python 3.13 needs to be installed"
                  echo "skip-python-setup=false" >> $GITHUB_OUTPUT
                fi
            
      - name: Set up Python
        uses: actions/setup-python@v2
        if: steps.python-check.outputs.skip-python-setup != 'true'
        with:
          python-version: '3.13'
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Build Api
        run: 
            make Build_api

      - name: Run tests
        run: |
            make test

      - name: Run Pylint
        run: |
          make Code_linting

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/restapi:{{github.sha}}

       