name: Build the PR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'code/**'
      - 'test/**'
      - 'DB/Schemas/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'code/**'
      - 'test/**'
      - 'DB/Schemas/**'
    branches:
      - master
      - main  # Added main branch for completeness
  workflow_dispatch:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual build request'

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Run tests
        run: |
            python ./test/test.py

      - name: Run Pylint
        run: |
          python -m flake8 .
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/restapi:${{ github.sha }}

       
